/**
 * Worker thread for Ollama API calls
 * This runs in a separate thread and can be terminated if it hangs
 */
import { parentPort, workerData } from 'worker_threads'

const OLLAMA_URL = 'http://localhost:11434/api/generate'

async function generateWithOllama() {
  const { model, prompt, options } = workerData

  try {
    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model,
        prompt,
        stream: false,
        options,
      }),
    })

    if (!response.ok) {
      throw new Error(`Ollama request failed: ${response.statusText}`)
    }

    const data = await response.json()
    const result = data.response?.trim()

    if (!result) {
      throw new Error('No response generated by Ollama')
    }

    parentPort.postMessage({ success: true, result })
  } catch (error) {
    parentPort.postMessage({ success: false, error: error.message })
  }
}

generateWithOllama()
